#version: '3'

services:
  app1:
    build: nginx_test
    container_name: nginx_test1
    command: sh -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - 8001:8000
    volumes:
      - ./nginx_test:/nginx_test

  app2:
    build: nginx_test
    container_name: nginx_test2
    command: sh -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - 8002:8000
    volumes:
      - ./nginx_test:/nginx_test  

  app3:
    build: nginx_test
    container_name: nginx_test3
    command: sh -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - 8003:8000
    volumes:
      - ./nginx_test:/nginx_test

  nginx:
    image:  nginx:alpine
    container_name: nginx
    ports:
      - 8000:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf